--
-- PostgreSQL database dump
--

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 17.0

-- Started on 2026-09-17 10:37:46

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 24697)
-- Name: Devices; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."Devices" (
    id integer NOT NULL,
    name text,
    "userAgent" text NOT NULL,
    "userId" integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."Devices" OWNER TO "open-auth-user";

--
-- TOC entry 216 (class 1259 OID 24696)
-- Name: Devices_id_seq; Type: SEQUENCE; Schema: public; Owner: open-auth-user
--

ALTER TABLE public."Devices" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Devices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24705)
-- Name: Domains; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."Domains" (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public."Domains" OWNER TO "open-auth-user";

--
-- TOC entry 218 (class 1259 OID 24704)
-- Name: Domains_id_seq; Type: SEQUENCE; Schema: public; Owner: open-auth-user
--

ALTER TABLE public."Domains" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Domains_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 24727)
-- Name: PasswordResetTokens; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."PasswordResetTokens" (
    id integer NOT NULL,
    "userId" integer NOT NULL,
    "tokenHash" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "usedAt" timestamp with time zone
);


ALTER TABLE public."PasswordResetTokens" OWNER TO "open-auth-user";

--
-- TOC entry 224 (class 1259 OID 24726)
-- Name: PasswordResetTokens_id_seq; Type: SEQUENCE; Schema: public; Owner: open-auth-user
--

ALTER TABLE public."PasswordResetTokens" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PasswordResetTokens_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24713)
-- Name: Permissions; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."Permissions" (
    id integer NOT NULL,
    level integer NOT NULL
);


ALTER TABLE public."Permissions" OWNER TO "open-auth-user";

--
-- TOC entry 220 (class 1259 OID 24712)
-- Name: Permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: open-auth-user
--

ALTER TABLE public."Permissions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Permissions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 24740)
-- Name: Sessions; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."Sessions" (
    id integer NOT NULL,
    "userId" integer NOT NULL,
    "deviceId" integer NOT NULL,
    "tokenHash" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "lastActivityAt" timestamp with time zone NOT NULL,
    "expiresAt" timestamp with time zone NOT NULL,
    "revokedAt" timestamp with time zone
);


ALTER TABLE public."Sessions" OWNER TO "open-auth-user";

--
-- TOC entry 226 (class 1259 OID 24739)
-- Name: Sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: open-auth-user
--

ALTER TABLE public."Sessions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sessions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 24772)
-- Name: UserDomains; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."UserDomains" (
    "userId" integer NOT NULL,
    "domainId" integer NOT NULL,
    "permissionId" integer NOT NULL
);


ALTER TABLE public."UserDomains" OWNER TO "open-auth-user";

--
-- TOC entry 223 (class 1259 OID 24719)
-- Name: Users; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."Users" (
    id integer NOT NULL,
    username text NOT NULL,
    email text NOT NULL,
    "passwordHash" text NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "deletedAt" timestamp with time zone
);


ALTER TABLE public."Users" OWNER TO "open-auth-user";

--
-- TOC entry 222 (class 1259 OID 24718)
-- Name: Users_id_seq; Type: SEQUENCE; Schema: public; Owner: open-auth-user
--

ALTER TABLE public."Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 24691)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "open-auth-user";

--
-- TOC entry 228 (class 1259 OID 24757)
-- Name: user_devices; Type: TABLE; Schema: public; Owner: open-auth-user
--

CREATE TABLE public.user_devices (
    devicesid integer NOT NULL,
    userid integer NOT NULL
);


ALTER TABLE public.user_devices OWNER TO "open-auth-user";

--
-- TOC entry 3485 (class 0 OID 24697)
-- Dependencies: 217
-- Data for Name: Devices; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--



--
-- TOC entry 3487 (class 0 OID 24705)
-- Dependencies: 219
-- Data for Name: Domains; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--

INSERT INTO public."Domains" VALUES (1, 'dominioTest');


--
-- TOC entry 3493 (class 0 OID 24727)
-- Dependencies: 225
-- Data for Name: PasswordResetTokens; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--



--
-- TOC entry 3489 (class 0 OID 24713)
-- Dependencies: 221
-- Data for Name: Permissions; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--

INSERT INTO public."Permissions" VALUES (1, 0);


--
-- TOC entry 3495 (class 0 OID 24740)
-- Dependencies: 227
-- Data for Name: Sessions; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--



--
-- TOC entry 3497 (class 0 OID 24772)
-- Dependencies: 229
-- Data for Name: UserDomains; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--

INSERT INTO public."UserDomains" VALUES (3, 1, 1);


--
-- TOC entry 3491 (class 0 OID 24719)
-- Dependencies: 223
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--

INSERT INTO public."Users" VALUES (3, 'admin', 'admin', '$2a$11$KudszP34FzcMNZLggar73eOS.KqfkvqzKjho.F4MsFN0LoG.xuTTi', '2026-09-16 12:55:31.67+00', NULL);


--
-- TOC entry 3483 (class 0 OID 24691)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260910155834_InitialCreate', '9.0.19');


--
-- TOC entry 3496 (class 0 OID 24757)
-- Dependencies: 228
-- Data for Name: user_devices; Type: TABLE DATA; Schema: public; Owner: open-auth-user
--



--
-- TOC entry 3503 (class 0 OID 0)
-- Dependencies: 216
-- Name: Devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: open-auth-user
--

SELECT pg_catalog.setval('public."Devices_id_seq"', 1, false);


--
-- TOC entry 3504 (class 0 OID 0)
-- Dependencies: 218
-- Name: Domains_id_seq; Type: SEQUENCE SET; Schema: public; Owner: open-auth-user
--

SELECT pg_catalog.setval('public."Domains_id_seq"', 1, true);


--
-- TOC entry 3505 (class 0 OID 0)
-- Dependencies: 224
-- Name: PasswordResetTokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: open-auth-user
--

SELECT pg_catalog.setval('public."PasswordResetTokens_id_seq"', 1, false);


--
-- TOC entry 3506 (class 0 OID 0)
-- Dependencies: 220
-- Name: Permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: open-auth-user
--

SELECT pg_catalog.setval('public."Permissions_id_seq"', 1, true);


--
-- TOC entry 3507 (class 0 OID 0)
-- Dependencies: 226
-- Name: Sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: open-auth-user
--

SELECT pg_catalog.setval('public."Sessions_id_seq"', 1, false);


--
-- TOC entry 3508 (class 0 OID 0)
-- Dependencies: 222
-- Name: Users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: open-auth-user
--

SELECT pg_catalog.setval('public."Users_id_seq"', 3, true);


--
-- TOC entry 3307 (class 2606 OID 24703)
-- Name: Devices PK_Devices; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Devices"
    ADD CONSTRAINT "PK_Devices" PRIMARY KEY (id);


--
-- TOC entry 3310 (class 2606 OID 24711)
-- Name: Domains PK_Domains; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Domains"
    ADD CONSTRAINT "PK_Domains" PRIMARY KEY (id);


--
-- TOC entry 3319 (class 2606 OID 24733)
-- Name: PasswordResetTokens PK_PasswordResetTokens; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."PasswordResetTokens"
    ADD CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY (id);


--
-- TOC entry 3312 (class 2606 OID 24717)
-- Name: Permissions PK_Permissions; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Permissions"
    ADD CONSTRAINT "PK_Permissions" PRIMARY KEY (id);


--
-- TOC entry 3324 (class 2606 OID 24746)
-- Name: Sessions PK_Sessions; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "PK_Sessions" PRIMARY KEY (id);


--
-- TOC entry 3331 (class 2606 OID 24776)
-- Name: UserDomains PK_UserDomains; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."UserDomains"
    ADD CONSTRAINT "PK_UserDomains" PRIMARY KEY ("userId", "domainId");


--
-- TOC entry 3316 (class 2606 OID 24725)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY (id);


--
-- TOC entry 3305 (class 2606 OID 24695)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3327 (class 2606 OID 24761)
-- Name: user_devices PK_user_devices; Type: CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT "PK_user_devices" PRIMARY KEY (devicesid, userid);


--
-- TOC entry 3308 (class 1259 OID 24792)
-- Name: IX_Domains_name; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE UNIQUE INDEX "IX_Domains_name" ON public."Domains" USING btree (name);


--
-- TOC entry 3317 (class 1259 OID 24793)
-- Name: IX_PasswordResetTokens_userId; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE INDEX "IX_PasswordResetTokens_userId" ON public."PasswordResetTokens" USING btree ("userId");


--
-- TOC entry 3320 (class 1259 OID 24794)
-- Name: IX_Sessions_deviceId; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE INDEX "IX_Sessions_deviceId" ON public."Sessions" USING btree ("deviceId");


--
-- TOC entry 3321 (class 1259 OID 24795)
-- Name: IX_Sessions_tokenHash; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE UNIQUE INDEX "IX_Sessions_tokenHash" ON public."Sessions" USING btree ("tokenHash");


--
-- TOC entry 3322 (class 1259 OID 24796)
-- Name: IX_Sessions_userId; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE INDEX "IX_Sessions_userId" ON public."Sessions" USING btree ("userId");


--
-- TOC entry 3328 (class 1259 OID 24798)
-- Name: IX_UserDomains_domainId; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE INDEX "IX_UserDomains_domainId" ON public."UserDomains" USING btree ("domainId");


--
-- TOC entry 3329 (class 1259 OID 24799)
-- Name: IX_UserDomains_permissionId; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE INDEX "IX_UserDomains_permissionId" ON public."UserDomains" USING btree ("permissionId");


--
-- TOC entry 3313 (class 1259 OID 24800)
-- Name: IX_Users_email; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE UNIQUE INDEX "IX_Users_email" ON public."Users" USING btree (email);


--
-- TOC entry 3314 (class 1259 OID 24801)
-- Name: IX_Users_username; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE UNIQUE INDEX "IX_Users_username" ON public."Users" USING btree (username);


--
-- TOC entry 3325 (class 1259 OID 24797)
-- Name: IX_user_devices_userid; Type: INDEX; Schema: public; Owner: open-auth-user
--

CREATE INDEX "IX_user_devices_userid" ON public.user_devices USING btree (userid);


--
-- TOC entry 3332 (class 2606 OID 24734)
-- Name: PasswordResetTokens FK_PasswordResetTokens_Users_userId; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."PasswordResetTokens"
    ADD CONSTRAINT "FK_PasswordResetTokens_Users_userId" FOREIGN KEY ("userId") REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- TOC entry 3333 (class 2606 OID 24747)
-- Name: Sessions FK_Sessions_Devices_deviceId; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "FK_Sessions_Devices_deviceId" FOREIGN KEY ("deviceId") REFERENCES public."Devices"(id) ON DELETE CASCADE;


--
-- TOC entry 3334 (class 2606 OID 24752)
-- Name: Sessions FK_Sessions_Users_userId; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."Sessions"
    ADD CONSTRAINT "FK_Sessions_Users_userId" FOREIGN KEY ("userId") REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- TOC entry 3337 (class 2606 OID 24777)
-- Name: UserDomains FK_UserDomains_Domains_domainId; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."UserDomains"
    ADD CONSTRAINT "FK_UserDomains_Domains_domainId" FOREIGN KEY ("domainId") REFERENCES public."Domains"(id) ON DELETE CASCADE;


--
-- TOC entry 3338 (class 2606 OID 24782)
-- Name: UserDomains FK_UserDomains_Permissions_permissionId; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."UserDomains"
    ADD CONSTRAINT "FK_UserDomains_Permissions_permissionId" FOREIGN KEY ("permissionId") REFERENCES public."Permissions"(id) ON DELETE CASCADE;


--
-- TOC entry 3339 (class 2606 OID 24787)
-- Name: UserDomains FK_UserDomains_Users_userId; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public."UserDomains"
    ADD CONSTRAINT "FK_UserDomains_Users_userId" FOREIGN KEY ("userId") REFERENCES public."Users"(id) ON DELETE CASCADE;


--
-- TOC entry 3335 (class 2606 OID 24762)
-- Name: user_devices FK_user_devices_Devices_devicesid; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT "FK_user_devices_Devices_devicesid" FOREIGN KEY (devicesid) REFERENCES public."Devices"(id) ON DELETE CASCADE;


--
-- TOC entry 3336 (class 2606 OID 24767)
-- Name: user_devices FK_user_devices_Users_userid; Type: FK CONSTRAINT; Schema: public; Owner: open-auth-user
--

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT "FK_user_devices_Users_userid" FOREIGN KEY (userid) REFERENCES public."Users"(id) ON DELETE CASCADE;


-- Completed on 2026-09-17 10:37:47

--
-- PostgreSQL database dump complete
--

