@open_auth_backend_HostAddress_http = http://localhost:8080
@open_auth_backend_HostAddress_https = https://localhost:8081

GET {{open_auth_backend_HostAddress_http}}/login
Accept: application/json

###


GET {{open_auth_backend_HostAddress_https}}/login
Accept: application/json

###


GET {{open_auth_backend_HostAddress_https}}/login/DefaultLogin
Accept: application/json

###


POST {{open_auth_backend_HostAddress_https}}/login/auth
Accept: application/json
Content-Type: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/154.0.0.0

{
	"emailOrUsername": "admin",
	"password": "admin"
}

###