name: open-auth-backend
services:
  postgres:
    image: postgres:16
    container_name: postgres16

    environment:
      POSTGRES_DB: open-auth-db
      POSTGRES_USER: open-auth-user
      POSTGRES_PASSWORD: open-auth-psw

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: